[context.production.environment]
  HUGO_VERSION = "0.115.4"
  HUGO_GOOGLE_ANALYTICS_ID = "G-1X61G0K9F1"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.115.4"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.115.4"
